version: '3'
services:
  nuxt:
    container_name: snakeware
    restart: always
    build:
        context: .
    volumes:
      - ./components:/vue/components
    ports:
      - "3500:3000"
    command: ["npm", "run", "dev"]
